# Generated by Django 5.1.3 on 2024-11-26 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IMAPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Server Name")),
                ("host", models.CharField(max_length=255, verbose_name="Host")),
                ("port", models.IntegerField(default=993, verbose_name="Port")),
                ("username", models.CharField(max_length=255, verbose_name="Username")),
                ("password", models.CharField(max_length=255, verbose_name="Password")),
                ("use_ssl", models.BooleanField(default=True, verbose_name="Use SSL")),
                (
                    "folder",
                    models.CharField(
                        default="INBOX", max_length=100, verbose_name="Folder"
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Sync"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imap_servers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "IMAP Server",
                "verbose_name_plural": "IMAP Servers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Message ID"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Subject"
                    ),
                ),
                ("sender", models.CharField(max_length=255, verbose_name="Sender")),
                (
                    "recipient",
                    models.CharField(max_length=255, verbose_name="Recipient"),
                ),
                ("date", models.DateTimeField(verbose_name="Date")),
                ("body_text", models.TextField(blank=True, verbose_name="Body Text")),
                ("body_html", models.TextField(blank=True, verbose_name="Body HTML")),
                (
                    "raw_headers",
                    models.TextField(blank=True, verbose_name="Raw Headers"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "imap_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="emails.imapserver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Emails",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["message_id"], name="emails_emai_message_48f464_idx"
                    ),
                    models.Index(fields=["date"], name="emails_emai_date_bd689a_idx"),
                    models.Index(
                        fields=["sender"], name="emails_emai_sender_a54e55_idx"
                    ),
                    models.Index(
                        fields=["subject"], name="emails_emai_subject_35730d_idx"
                    ),
                ],
            },
        ),
    ]
