# Generated by Django 5.1.3 on 2024-11-27 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imapserver",
            name="folder",
        ),
        migrations.AddField(
            model_name="email",
            name="folder",
            field=models.CharField(default=0, max_length=255, verbose_name="Folder"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="email",
            name="in_reply_to",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="In Reply To"
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="references",
            field=models.TextField(blank=True, verbose_name="References"),
        ),
        migrations.AddField(
            model_name="email",
            name="thread_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Thread ID"
            ),
        ),
        migrations.AddField(
            model_name="imapserver",
            name="exclude_trash",
            field=models.BooleanField(
                default=True,
                help_text="Exclude trash folder from syncing",
                verbose_name="Exclude Trash",
            ),
        ),
        migrations.AddField(
            model_name="imapserver",
            name="folders_to_sync",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of folders to sync. Leave empty for all folders except trash.",
                verbose_name="Folders to Sync",
            ),
        ),
        migrations.AddField(
            model_name="imapserver",
            name="sync_limit_type",
            field=models.CharField(
                choices=[
                    ("all", "All Messages"),
                    ("last_n", "Last N Messages"),
                    ("days", "Messages from Last N Days"),
                    ("weeks", "Messages from Last N Weeks"),
                    ("months", "Messages from Last N Months"),
                ],
                default="all",
                max_length=20,
                verbose_name="Sync Limit Type",
            ),
        ),
        migrations.AddField(
            model_name="imapserver",
            name="sync_limit_value",
            field=models.IntegerField(
                blank=True,
                help_text="Number of messages or time period to sync",
                null=True,
                verbose_name="Sync Limit Value",
            ),
        ),
        migrations.AddIndex(
            model_name="email",
            index=models.Index(
                fields=["thread_id"], name="emails_emai_thread__f79da4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="email",
            index=models.Index(fields=["folder"], name="emails_emai_folder_d7ac4b_idx"),
        ),
    ]
