# Generated by Django 5.1.3 on 2024-11-27 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_auto_20241127_0530"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="message_id",
            field=models.CharField(
                help_text="Unique identifier for the email",
                max_length=255,
                verbose_name="Message ID",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="email",
            unique_together={("user", "imap_server", "message_id", "folder")},
        ),
    ]
